'use strict';

module.exports =
  angular.module('Pando', [
    'ui.router',
    'angularGrid',
    'ngAnimate',
    'videosharing-embed',
    'youtube-embed',
    'duScroll',
    //load extra external dependencies here, e.g.:
    //'ngAnimate',
    //html templates in $templateCache generated by Gulp:
    require('../../../tmp/templates').name,
    //useful directives, filters, services shared across the app
    require('../common').name,
    //example app module:
    require('./home').name,
    require('./chronicles').name,
    require('./category').name,
    require('./about').name,
    require('./post').name,
    //load extra app modules here, e.g.:
    //require('./frontend').name,
    //require('./admin').name
  ])
  .run(function ($rootScope, $state, $document, $timeout, $stateParams) {
    $rootScope.$on('$stateChangeSuccess', function (ev, to, toParams, from, fromParams) {
      $rootScope.previousState = from.name;
      $rootScope.previousParams = fromParams.category;
    });
  });